import { access, mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { constants } from "node:fs";
import path from "node:path";
import { assertValidConfig, navigationHosts } from "./config.js";
import type { AppConfig, BuildResult } from "./types.js";

const GENERATED_BY = "Generated by Webtoapp Studio. Customize with care.";

export interface GenerateOptions {
  force?: boolean;
}

export async function writeGeneratedProject(rawConfig: Partial<AppConfig>, outputDirectory: string, options: GenerateOptions = {}): Promise<BuildResult> {
  const config = assertValidConfig(rawConfig);
  const destination = path.resolve(outputDirectory);
  await prepareOutput(destination, Boolean(options.force));

  const files: Array<[string, string]> = [
    ["package.json", packageJson(config)],
    ["webtoapp.config.json", stringify(config)],
    ["main.cjs", mainProcess(config)],
    ["preload.cjs", preloadScript()],
    ["README.md", generatedReadme(config)],
    [".gitignore", "node_modules/\nrelease/\ndist/\n*.log\n"],
  ];

  await Promise.all(files.map(async ([name, content]) => {
    const file = path.join(destination, name);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content, "utf8");
  }));

  return { outputDirectory: destination, files: files.map(([name]) => name) };
}

async function prepareOutput(destination: string, force: boolean): Promise<void> {
  try {
    await access(destination, constants.F_OK);
    const contents = await readdir(destination);
    if (contents.length > 0 && !force) {
      throw new Error(`Output directory is not empty: ${destination}. Pass --force to replace it.`);
    }
    if (force) await rm(destination, { recursive: true, force: true });
  } catch (error) {
    if (error instanceof Error && !/ENOENT/.test(String((error as NodeJS.ErrnoException).code))) throw error;
  }
  await mkdir(destination, { recursive: true });
}

function stringify(config: AppConfig): string {
  return `${JSON.stringify({ ...config, behavior: { ...config.behavior, allowNavigation: navigationHosts(config) } }, null, 2)}\n`;
}

function packageName(appId: string): string {
  return appId.toLowerCase().replace(/[^a-z0-9-]+/g, "-").replace(/^-+|-+$/g, "") || "webtoapp-app";
}

function packageJson(config: AppConfig): string {
  const manifest = {
    name: packageName(config.appId),
    version: "1.0.0",
    private: true,
    description: `Desktop wrapper for ${config.website}`,
    main: "main.cjs",
    scripts: {
      start: "electron .",
      dev: "electron .",
      package: "electron-builder --publish never",
    },
    devDependencies: {
      electron: "^33.2.1",
      "electron-builder": "^25.1.8",
    },
    build: {
      appId: config.appId,
      productName: config.appName,
      directories: { output: "release" },
      files: ["main.cjs", "preload.cjs", "webtoapp.config.json", "package.json"],
      linux: { target: ["AppImage", "deb"], category: "Network" },
      mac: { target: ["dmg", "zip"], category: "public.app-category.productivity" },
      win: { target: ["nsis", "zip"] },
      nsis: { oneClick: false, allowToChangeInstallationDirectory: true },
    },
  };
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function mainProcess(config: AppConfig): string {
  const allowedHosts = JSON.stringify(navigationHosts(config));
  return `"use strict";
// ${GENERATED_BY}
const { app, BrowserWindow, shell, ipcMain } = require("electron");
const path = require("node:path");
const config = require("./webtoapp.config.json");

const allowedHosts = new Set(${allowedHosts});

function isAllowedNavigation(rawUrl) {
  try {
    const url = new URL(rawUrl);
    return (url.protocol === "https:" || url.protocol === "http:") && allowedHosts.has(url.hostname.toLowerCase());
  } catch {
    return false;
  }
}

function createWindow() {
  const window = new BrowserWindow({
    width: config.window.width,
    height: config.window.height,
    minWidth: config.window.minWidth,
    minHeight: config.window.minHeight,
    backgroundColor: config.themeColor,
    autoHideMenuBar: !config.behavior.showMenuBar,
    show: false,
    webPreferences: {
      preload: path.join(__dirname, "preload.cjs"),
      contextIsolation: true,
      nodeIntegration: false,
      sandbox: true,
      webSecurity: true,
    },
  });

  window.once("ready-to-show", () => window.show());
  window.webContents.setWindowOpenHandler(({ url }) => {
    if (config.behavior.openExternalLinks && /^https?:/i.test(url)) shell.openExternal(url);
    return { action: "deny" };
  });
  window.webContents.on("will-navigate", (event, url) => {
    if (!isAllowedNavigation(url)) {
      event.preventDefault();
      if (config.behavior.openExternalLinks && /^https?:/i.test(url)) shell.openExternal(url);
    }
  });
  window.webContents.on("will-redirect", (event, url) => {
    if (!isAllowedNavigation(url)) event.preventDefault();
  });
  window.loadURL(config.website);
}

app.whenReady().then(() => {
  app.setAppUserModelId(config.appId);
  ipcMain.handle("webtoapp:openExternal", (_event, url) => {
    if (typeof url === "string" && /^https?:\/\//i.test(url)) return shell.openExternal(url);
    return undefined;
  });
  createWindow();
  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") app.quit();
});
`;
}

function preloadScript(): string {
  return `"use strict";
// ${GENERATED_BY}
const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("webtoapp", Object.freeze({
  isDesktop: true,
  platform: process.platform,
  openExternal: (url) => {
    if (typeof url === "string" && /^https?:\/\//i.test(url)) return ipcRenderer.invoke("webtoapp:openExternal", url);
    return Promise.resolve();
  },
}));
`;
}

function generatedReadme(config: AppConfig): string {
  return `# ${config.appName}

${GENERATED_BY}

This is a desktop wrapper for [${config.website}](${config.website}).

## Run locally

\`\`\`bash
npm install
npm start
\`\`\`

## Build an installer

\`\`\`bash
npm run package
\`\`\`

Your wrapper uses a sandboxed renderer, context isolation, and a navigation allow-list. Change \`webtoapp.config.json\` and regenerate with Webtoapp Studio rather than weakening Electron security settings.
`;
}
